### ISSUE TITLE
Question about how to setup the config files

### ISSUE THREAD

**Issue by DatrixTheHybridShadowWolf** [CriochDev/Fluid-Sieve#4]
I noticed you said that you could put the json files into a folder in the minecraft/loot_table folder, but due to my brain I am unaware of how to setup the config file for getting said items within the block underneath while I have flowing water going through the seive. Is there an example file I could use for reference in regards to the setup?

**Comment by CriochDev** [comment]
I'm not quite sure what your question is. Are you asking about the actual config? Here's the builtin one for [water](https://github.com/CriochDev/Fluid-Sieve/blob/main/src/main/resources/data/minecraft/loot_table/sieve/water.json)
