### ISSUE TITLE
1.21.3 update

### ISSUE THREAD

**Issue by vico93** [CriochDev/Fluid-Sieve#5]
Hi! Is an 1.21.3 update in the plans?

Thanks a lot for this mod!

**Comment by CriochDev** [comment]
Yes. I will be working on it this week.

**Comment by vico93** [comment]
Any updates @CriochDev ?

**Comment by CriochDev** [comment]
My apologies, I've been distracted by the US elections.

I'm currently working on it; trying to fix the loot generation because they changed it again.

**Comment by CriochDev** [comment]
@vico93 This has been updated to 1.21.3
